### ISSUE TITLE
FEATURE REQUEST:  Path to an Open-Source engine backend?

### ISSUE THREAD

**Issue by clort81** [JosiahJack/Citadel#312]
How deeply hooked into Unity3D is the project now?

A FOSS engine like godot3 or dhewm3 would open the project to millions of arm-linux targets - this class of devices has little competition (are not as crowded by other games) as x86 and android targets.

Since the original game was primitive by today's standards, there's no content requiring the bling and posh of Unity.

Thoughts?

**Comment by JosiahJack** [comment]
Deep and not deep.  Most of the data and logic is easily transferable.  The main issues with a full transfer would be the user interface, reliance on a few proprietary post-processing effects (notably my hacky way of implementing berserk patch hallucination effects depending on an outdated PP stack, heh), and heavy dependence on Unity's integration with PhysX for the physics engine.  It's not impossible, but would unfortunately be quite the undertaking since most of the UI is hand placed Unity GameObjects rather than something that is placed via scripting...a small regret of mine since moddability has always been an end goal at some point; hind sight is 20-20 etc.  The post-processing and physics could easily be replaced with simple API calls into whatever a different engine has; the UI would be the main headache and is a huge part of the game atmosphere and story.

Currently the plan is to only provide a Windows, Mac, and Linux build (Deb based at least, might test it in an Arch distro).

Lately I've been working on fixing a major issue with lighting that causes horrendous performance late in the game.  Trying to avoid having players get most of the way only to get stuck because their rig is a potato.
